name: On Host Tests
description: Runs on-host tests.
inputs:
  test_artifacts_key:
    description: "Artifact key used to store test artifacts."
    required: true
  results_dir:
    description: "Path to directory where test results are saved."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
    - name: Extract Artifacts
      shell: bash
      run: |
        set -x
        mkdir -p ${GITHUB_WORKSPACE}/unit_test
        cd ${GITHUB_WORKSPACE}/unit_test
        tar xvf ${GITHUB_WORKSPACE}/test_artifacts.tar.xz
    - name: Run Tests
      id: run-tests
      shell: bash
      env:
        GTEST_OUTPUT_ARG: ${{ inputs.results_dir }}
        XVFB_SERVER_ARGS: "-screen 0 1920x1080x24i +render +extension GLX -noreset"
      run: |
        set -x
        cd ${GITHUB_WORKSPACE}/unit_test
        for test_binary in $(ls -d out/**/*tests); do
          # TODO(b/372303096): Need dedicated xvfb runner.
          xvfb-run -a --server-args=${XVFB_SERVER_ARGS} ./$test_binary --gtest_output="xml:${RESULTS_DIR}/${test_binary}_testoutput.xml"
        done
