name: On Device Test
description: Runs on-device tests.

runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: |
        pip3 install grpcio==1.38.0 grpcio-tools==1.38.0
      shell: bash
    - name: Generate gRPC files
      run: |
        python -m grpc_tools.protoc -Itools/ --python_out=tools/ --grpc_python_out=tools/ tools/on_device_tests_gateway.proto
      shell: bash
    - name: Set Up Cloud SDK
      uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
    - name: Set env vars
      run: |
        echo "PROJECT_NAME=$(gcloud config get-value project)" >> $GITHUB_ENV
  
        # Test results and logs
        echo "GCS_RESULTS_PATH=gs://cobalt-unittest-storage/results/${{ matrix.name }}/${{ github.run_id }}" >> $GITHUB_ENV

        # Dimension env
        if [ "${{ matrix.dimension }}" != "null" ]; then
          echo "DIMENSION=${{ matrix.dimension }}" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Run ${{ env.SHARD_NAME }} Tests on ${{ matrix.platform }} Platform
      env:
        GCS_PATH: gs://${{ env.PROJECT_NAME }}-test-artifacts/${{ github.workflow }}/${{ github.run_number }}/${{ matrix.platform }}_${{ matrix.config }}
      run: |
        set -uxe
        python3 -u tools/on_device_tests_gateway_client.py \
          --platform_json "${GITHUB_WORKSPACE}/src/.github/config/${{ matrix.platform}}.json" \
          --filter_json_dir "${GITHUB_WORKSPACE}/src/cobalt/testing/${{ matrix.platform}}" \
          --token ${GITHUB_TOKEN} \
          ${DIMENSION:+"--dimension" "$DIMENSION"} \
          ${ON_DEVICE_TEST_ATTEMPTS:+"--test_attempts" "$ON_DEVICE_TEST_ATTEMPTS"} \
          --archive_path "${GCS_PATH}/artifacts.tar" \
          --gcs_result_path "${GCS_RESULTS_PATH}" \
          trigger \
      shell: bash
    - name: Download ${{ matrix.platform }} Test Results
      if: always() && env.TEST_TYPE == 'unit_test'
      run: |
        # Don't break on error (-e), some commands are expected to fail.
        set -ux

        COBALT_LOGS_DIR="${GITHUB_WORKSPACE}/cobalt_logs"
        UNIT_TEST_RESULT_PATH="${GITHUB_WORKSPACE}/unit-test-results"
        COBALT_XMLS_FILENAME="cobalt_xmls.zip"

        # Forward environment variables for uploading artifacts in later steps.
        echo "UNIT_TEST_RESULT_PATH=${UNIT_TEST_RESULT_PATH}" >> $GITHUB_ENV
        echo "COBALT_LOGS_DIR=${COBALT_LOGS_DIR}" >> $GITHUB_ENV

        mkdir -p "${GITHUB_WORKSPACE}/test_results"
        cd "${GITHUB_WORKSPACE}/test_results"

        i=0
        # Try downloading the results for 6x 10 seconds before giving up.
        while [ $i -lt 6 ]; do
          # The results are uploaded after the test has completed.
          sleep 10

          # The log files are named by the device lab test driver.
          COBALT_ERROR_LOG_FILENAME="webDriverTestLog.ERROR"
          COBALT_INFO_LOG_FILENAME="webDriverTestLog.INFO"

          # This command will fail until the results have been uploaded.
          gsutil cp "${GCS_RESULTS_PATH}/${COBALT_ERROR_LOG_FILENAME}" .
          gsutil cp "${GCS_RESULTS_PATH}/${COBALT_INFO_LOG_FILENAME}" .
          gsutil cp "${GCS_RESULTS_PATH}/${COBALT_XMLS_FILENAME}" .

          # Break if all files were downloaded.
          if [[ -f "${COBALT_XMLS_FILENAME}" && -f "${COBALT_ERROR_LOG_FILENAME}" && -f "${COBALT_INFO_LOG_FILENAME}" ]]; then
            break
          fi

          i=$(( ${i} + 1 ))
        done

        # Rename log files for archiving to not expose legacy weirdness.
        mkdir -p "${COBALT_LOGS_DIR}/${{ matrix.platform }}/"
        cp "${COBALT_ERROR_LOG_FILENAME}" "${COBALT_LOGS_DIR}/${{ matrix.platform }}/stderr_${{ matrix.shard }}.log"
        cp "${COBALT_INFO_LOG_FILENAME}" "${COBALT_LOGS_DIR}/${{ matrix.platform }}/stdout_${{ matrix.shard }}.log"

        # Prepare unit test results for DataDog upload.
        RESULT_PATH=${UNIT_TEST_RESULT_PATH}/${{ matrix.platform }}/${{ matrix.shard }}/
        mkdir -p ${RESULT_PATH}

        # Set tags for test differentiation.
        tags="os.platform:${{ matrix.platform }}"
        echo $tags > ${UNIT_TEST_RESULT_PATH}/${{ matrix.platform }}/TAGS

        unzip ${COBALT_XMLS_FILENAME} -d ${RESULT_PATH}
      shell: bash
    - name: Archive Unit Test Logs
      uses: actions/upload-artifact@v3
      if: always() && env.TEST_TYPE == 'unit_test'
      with:
        name: Device logs
        path: ${{ env.COBALT_LOGS_DIR }}/
    - name: Archive Unit Test Results
      uses: actions/upload-artifact@v3
      if: always() && env.TEST_TYPE == 'unit_test'
      with:
        name: unit-test-results
        path: ${{ env.UNIT_TEST_RESULT_PATH }}/
    - name: Print device logs
      if: always()
      run: |
        if ls ${COBALT_LOGS_DIR}/**/*.log 1> /dev/null 2>&1; then
          cat ${COBALT_LOGS_DIR}/**/*.log
        else
          echo "No device logs found"
        fi
      shell: bash
